---
theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
title: Essence of chocolate
author: Gillian Sydney Widmer
description: I will teach you the importance of chocolate in your life
logo: C:\Users\gilli\OneDrive - Kantonsschule Frauenfeld\Informatik
---
